### ISSUE TITLE
How am i gonna use it?

### ISSUE THREAD

**Issue by Zaid-maker** [gayanvoice/top-github-users#1]
How to use it add a setup

**Comment by gayanvoice** [comment]
#### 1. Folk the repository
Give it any name.
#### 2. Create a personal access token
Go to settings>Developer settings > Personal access tokens
Click on the "Generate new token" button and give it any name.
Select all options in `repo`, `workflow`, `read:org` in `admin:org` and `read:user` in `user` and click on "Generate token" button.
Copy the personal access token.
#### 3. Create a repository secret
Go to your repository.
Click on Settings > Secrets and click on the "New repository secret" button.
Enter "CUSTOM_TOKEN" in name input and paste the personal access token in value and then click on the "Add secret" button.
#### 4. Run the action
Go to your repository.
Click on Actions and select Top GitHub Users.
Click on "Run workflow" button.

**Comment by Zaid-maker** [comment]
Ok dude thank you so muchh
