### ISSUE TITLE
List of Pakistan is outdated!

### ISSUE THREAD

**Issue by Qazalbash** [gayanvoice/top-github-users#123]
I changed my username last year. It is still showing the old one.

**Comment by biud436** [comment]
Unfortunately the list doesn't seem to have been updated in years. Only the date will be changed.

**Comment by Qazalbash** [comment]
It would be great if they do it. I would leave this issue opened, until he gets time and fixed it.

**Comment by hbourgeot** [comment]
@Qazalbash Unfortunately, the last time several countries were updated was before September last year.

**Comment by Qazalbash** [comment]
The list has been updated in 4bd9d40b556ca625f72199e1c3d4c6fdb5879542 and shows my updated username.
