### ISSUE TITLE
publish as GitHub pages?

### ISSUE THREAD

**Issue by maifeeulasad** [gayanvoice/top-github-users#2]
if you create a `gh-pages` branch and configure it.

It should be hosted somewhere in : **gayanvoice.github.io/top-github-users**

**Comment by gayanvoice** [comment]
Yes, there is a ranking map https://gayanvoice.github.io/top-github-users/index.html I haven't set all markdowns to GitHub pages because it is not recorded in GitHub Insights.

**Comment by maifeeulasad** [comment]
Ok, thanks. I've created one, here: https://maifeeulasad.github.io/top-github-users/, from your repo, I just forked and created a `gh-pages` branch.

Although, it needs more work to be done. Like:
 - Currently, those links on the page I mentioned takes me to GitHub readme, not to a GitHub page.

**Comment by gayanvoice** [comment]
Awesome, I checked your GitHub pages.  Yes, it's a GitHub Action. This repository https://github.com/gayanvoice/top-github-users-action is the source behind it. You can tweak it a little bit.
