### ISSUE TITLE
Add "San Marino" as a country

### ISSUE THREAD

**Issue by maggicl** [gayanvoice/top-github-users#3]
This repo seems very cool, good idea :+1: ! However, I've noticed that in the list of countries you miss the _Most Serene Republic of San Marino_, a sovreign microstate located as an enclave of the italian region of Emilia Romagna. Here is more about the country: 

- https://en.wikipedia.org/wiki/San_Marino
- https://www.youtube.com/watch?v=EKnhZSzp_lM
- https://www.youtube.com/watch?v=fsM3qqxA_6g

**Comment by gayanvoice** [comment]
There are very few users from San Marino. You can check it out https://github.com/search?o=desc&q=location%3Amarino&s=followers&type=Users

**Comment by warman69** [comment]
I for one very much appreciate this contribution, I don't see why San Marinoers should be discriminated. If there's not many of them, this is yet one more reason why we should support and encourage more San Marino developers to contribute to all the awesome open source projects on GitHub

**Comment by gayanvoice** [comment]
Added San Marino https://github.com/gayanvoice/top-github-users/blob/main/markdown/public_contributions/san_marino.md
