### ISSUE TITLE
How to check why someone is not in the list?

### ISSUE THREAD

**Issue by daKmoR** [gayanvoice/top-github-users#9]
I thought I should be part of the [Austria](https://github.com/gayanvoice/top-github-users/blob/main/markdown/public_contributions/austria.md) list?

Having ~600+ contributions and 100+ followers I think I should be somewhere in that top 1000 list (given that it starts with 1 public code contribution)

I thought maybe it's me not having my location set to "Vienna, Austria" before... so I did that and waiter for ~12 hours (it seems to update every hour?)... but I checked just now, and still not in there 🤔

do I need to do something more or just wait more? 🤔

**Comment by dongphuchaitrieu** [comment]
Curious the same thing

**Comment by daKmoR** [comment]
I'm there now 👍 

seems the location needs to be correct and then it takes a few days 🙈
